# Aula 09 - Arrays e Matrizes

In [1]:
import numpy as np # Manipulação de vetores e matrizes multidimensionais

### Vetores unidimensionais

In [2]:
x = np.array([1, 2, 3]) # Não é mutável, lembra a tupla (Lista são mutáveis)
print(x)

[1 2 3]


In [3]:
# Array é sempre de um tipo
y = np.array([1, 'caio', 3]) # Se um elemento for string, todos serão
print(y)

['1' 'caio' '3']


In [4]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

print(a + b) # Lista em python teria concatenado os dois vetores

[2 4 6]


In [5]:
x = np.zeros((5))
print(x)

[0. 0. 0. 0. 0.]


In [6]:
x = np.ones((5))
print(x)

[1. 1. 1. 1. 1.]


In [7]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
print(x[2:])

[3 4 5 6 7]


### Vetores multidimensionais

In [8]:
x = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(x)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [9]:
x[0]

array([1, 2, 3])

In [10]:
x[0][1]

2

In [11]:
x = np.array([[1, 2, 3]]*10)
print(x)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
x = np.zeros((5, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
x = np.ones((5, 5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# Para matriz quadratica (Matriz identidade)
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [16]:
x = np.arange(5, 10, 2)
print(x)

[5 7 9]


# Aula 10 - Operações com matrizes

In [17]:
x = np.array([[1, 2, 3]]*5)
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [18]:
y = np.array([[2, 2, 2]]*5)
y

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [19]:
x+y

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [20]:
x-y

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [21]:
x/y

array([[0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5]])

In [22]:
x*y

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])